name: Generate DocC
# This Github Action generates the DocC documentation for the current repo
# Then pushes this newly generated `.doccarchive` to a second repo
# Netlify is configured to pick up any changes to this second repo and serve the doc online!

on:
  push:
    branches: [ main ]
    # we'll start this action on every push to main
    
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-12
    # we need to run eveything on macOS, as we need to have Xcode installed
    
    steps:
    - name: Use Xcode 14.0.1
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0.1'
    
    # 1st, the Action will clone this repo (that contains the code)
    - name: Git Checkout
      uses: actions/checkout@v3
      with:
        path: 'mainBranch'
    # now we'll build the documentation
    - name: Build Doc Bundle 📗
      run: |
          echo "🚀 Starting building Documentation"
          
          cd mainBranch
          
          # You can print out which version of Xcode is used in this GH Action with:
          # xcodebuild -version
          
          # Build the documentation bundle
          xcodebuild docbuild -scheme kycDAO-SDK -derivedDataPath ./docbuild -destination 'platform=iOS Simulator,OS=latest,name=iPhone 13 mini' -clonedSourcePackagesDirPath ./../SPM/docbuild > build_output.txt
          
          # I'm redirecting all output from building the project and docs to build_output.txt
          # If you want to see it (or need to debug some problem), uncomment next line
          # cat build_output.txt
          
          cd ..
          
    # Generate static HTML docs
    - name: Generate static HTML docs 📖
      run: |
      
          # Doc is built, but it's inside docbuild, let's find it
          DOCC_DIR=`find ./mainBranch/docbuild -type d -iname "KycDao.doccarchive"`
          
          echo "Copying DocC archives to doc_archives..."
          mkdir ./doc_archives
          cp -R "$DOCC_DIR" ./doc_archives
          
          echo "$DOCC_DIR"
          
          $(xcrun --find docc) process-archive transform-for-static-hosting --help
          
          xcrun --find docc
          xcrun xcodebuild -version
          
          mkdir ./docs
          
          $(xcrun --find docc) process-archive transform-for-static-hosting ./doc_archives/KycDao.doccarchive --hosting-base-path kycdao-ios-sdk --output-path docs
          
          cp ./mainBranch/docsRes/index.html ./docs/index.html
          cp ./mainBranch/docsRes/index.html ./docs/documentation
          
    - uses: actions/upload-pages-artifact@v1
      with:
          path: docs/
          
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
